title: Compete McGill Summer Training 2019
description: Site for Compete McGill Summer Training Material
author: Compete McGill
logo: /static/img/logo.png
github: https://github.com/compete-mcgill
about: Summer 2019

baseurl: ""
url: "https://summer.compete-mcgill.ca"

allowsearch: true


enableTags: true
tagarray: []

pagination: 
  per_page: 6
  permalink: "/:num/"
  markdown: kramdown
  enabled: true

autopages:
  enabled: true
  categories:
    layouts:
      - 'project.html'
  
plugins: [jekyll-paginate-v2, jekyll-gist, jemoji]
