#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST != "false" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${GH_TOKEN}@github.com/Compete-McGill/compete-summer-2019.git --branch gh-pages _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push
cd _site
git config user.email "development@compete-mcgill.ca"
git config user.name "Compete Bot"
touch CNAME
echo "summer.compete-mcgill.ca" >> CNAME
git add --all
git add -f category/*
git commit -m "Travis #$TRAVIS_BUILD_NUMBER"
git push -f  origin gh-pages
git tag "releases/1.$TRAVIS_BUILD_NUMBER" 
git push -f --tags origin gh-pages
