#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${GH_TOKEN}@github.com/idodin/compete-summer-2019.git --branch gh-pages _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push
cd _site
git config user.email "imad.dodin@mail.mcgill.ca"
git config user.name "Imad Dodin"
git add --all
git tag "Release 1.$TRAVIS_BUILD_NUMBER" -a
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force --tags  origin gh-pages
